firstsite/firstsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from firstsite import settings
from mysite.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls')),
    path('users/', include('users.urls', namespace="users:login")),
    path('__debug__/', include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

firstsite/mysite/urls.py
from django.urls import path, register_converter
from . import views, converters

register_converter(converters.YearMonth, 'ye4mo2da2')

urlpatterns = [
    path('', views.MySiteHome.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('addpage/', views.AddPage.as_view(), name='addpage'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
    path('delete/<slug:slug>/', views.DeletePage.as_view(), name='delete_page'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login, name='login'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', views.MySiteCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', views.TagPostList.as_view(), name='tag'),
]

firstsite/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view( template_name="users/password_reset_confirm.html", success_url=reverse_lazy("users:password_reset_complete") ), name='password_reset_confirm'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"), name='password_reset_done'),
    path('password-reset/', PasswordResetView.as_view( template_name="users/password_reset_form.html", email_template_name="users/password_reset_email.html", success_url=reverse_lazy("users:password_reset_done") ), name='password_reset'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

firstsite/mysite/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


# Create your models here.
class PublishedModel(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=MySite.Status.PUBLISHED)


class UploadFiles(models.Model):
    file = models.FileField(upload_to='uploads_model')


def translit_to_eng(s: str) -> str:
    d = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e',
         'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'к': 'k', 'л': 'l',
         'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's',
         'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'c', 'ч': 'ch',
         'ш': 'sh', 'щ': 'shch', 'ь': '', 'ы': 'y', 'ъ': '', 'э': 'r',
         'ю': 'yu', 'я': 'ya'}
    return "".join(map(lambda x: d[x] if d.get(x, False) else x, s.lower()))


class MySite(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубликовано'

    title = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.SlugField(max_length=255, db_index=True, unique=True)
    content = models.TextField(blank=True, verbose_name="Текст описания")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    is_published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
                                       default=Status.DRAFT, verbose_name="Статус")
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='posts', verbose_name="Категории")
    tags = models.ManyToManyField('TagPost', blank=True, related_name='tags', verbose_name="Тэги")
    isbn = models.OneToOneField('ISBN', on_delete=models.SET_NULL,
                                null=True, blank=True, related_name='isbn', verbose_name="Номер ISBN")
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, related_name='posts', null=True, default=None)
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", default=None, blank=True, null=True, verbose_name="Фото")
    view_count = models.IntegerField(blank='True', default=0)
    objects = models.Manager()
    published = PublishedModel()

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def save(self, *args, **kwargs):
        self.slug = translit_to_eng(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    def __str__(self):
        return self.title


class ISBN(models.Model):
    number_13 = models.CharField(max_length=25)
    book_name = models.CharField(max_length=100)

    def __str__(self):
        return self.number_13


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name="Категория")
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'


class TagPost(models.Model):
    tag = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_slug': self.slug})

    def __str__(self):
        return self.tag

firstsite/mysite/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible

from .models import Category, ISBN, MySite
from django.core.validators import MinLengthValidator, MaxLengthValidator


class AddPostForm(forms.ModelForm):
    cat = forms.ModelChoiceField(queryset=Category.objects.all(),
                                 empty_label="Категория не выбрана",
                                 label="Категории")
    isbn = forms.ModelChoiceField(queryset=ISBN.objects.all(),
                                     required=False,
                                     empty_label="Не заполнено",
                                     label="Номер ISBN")

    class Meta:
        model = MySite
        fields = ['title', 'slug', 'content', 'photo',
                  'is_published', 'cat', 'isbn', 'tags']
        widgets = {'title': forms.TextInput(attrs={'class': 'form-input'}),
                   'content': forms.Textarea(attrs={'cols': 50, 'rows': 5}),
                   }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 50: raise ValidationError('Длина превышает 50 символов')
        return title


class UploadFileForm(forms.Form):
    file = forms.ImageField(label="Изображение")

firstsite/mysite/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseNotFound
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView

from mysite.forms import AddPostForm, UploadFileForm
from mysite.models import MySite, Category, TagPost, UploadFiles
import uuid

from mysite.utils import DataMixin
from users.forms import RegisterUserForm

menu = [{'title': "О сайте", 'url_name': 'about'},
        {'title': "Добавить статью", 'url_name': 'addpage'},
        {'title': "Обратная связь", 'url_name': 'contact'},
        {'title': "Войти", 'url_name': 'login'}
        ]


# Create your views here.
class TagPostList(DataMixin, ListView):
    template_name = 'mysite/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = TagPost.objects.get(slug=self.kwargs['tag_slug'])
        return self.get_mixin_context(context, title='Тег: ' + tag.tag)

    def get_queryset(self):
        return (MySite.published.filter(tags__slug=self.kwargs['tag_slug'])
                .select_related('cat'))


#def show_tag_postlist(request, tag_slug):
#    tag = get_object_or_404(TagPost, slug=tag_slug)
#    posts = tag.tags.filter(is_published=MySite.Status.PUBLISHED)
#    data = {
#        'title': f'Тег: {tag.tags}',
#        'menu': menu,
#        'posts': posts,
#        'cat_selected': None,
#    }
#    return render(request, 'mysite/index.html', context=data)


class MySiteCategory(DataMixin, ListView):
    template_name = 'mysite/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = context['posts'][0].cat
        return self.get_mixin_context(context,
                                      title='Категория - ' + cat.name,
                                      cat_selected=cat.id, )

    def get_queryset(self):
        return (MySite.published.filter(cat__slug=self.kwargs['cat_slug'])
                .select_related('cat'))


#def show_category(request, cat_slug):
#    category = get_object_or_404(Category, slug=cat_slug)
#    posts = MySite.published.filter(cat_id=category.pk)
#    data = {
#        'title': f'Рубрика: {category.name}',
#        'menu': menu,
#        'posts': posts,
#        'cat_selected': category.pk,
#    }
#    return render(request, 'mysite/index.html', context=data)


class ShowPost(DataMixin, DetailView):
    model = MySite
    template_name = 'mysite/post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, title=context['post'])

    def get_object(self, queryset=None):
        return (get_object_or_404
                (MySite.published,
                 slug=self.kwargs[self.slug_url_kwarg]))


#def show_post(request, post_slug):
#    post = get_object_or_404(MySite, slug=post_slug)
#    data = {'title': post.title,
#            'menu': menu,
#            'post': post,
#            'cat_selected': 0,
#            }
#    return render(request, 'mysite/post.html', context=data)


class MySiteHome(DataMixin, ListView):
    template_name = 'mysite/index.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        return self.get_mixin_context(super().get_context_data(**kwargs),
                                      title='Главная страница',
                                      cat_selected=0, )

    def get_queryset(self):
        return MySite.published.all().select_related('cat')

#def index(request):  # HttpRequest
#    posts = MySite.objects.filter(is_published=1)
#    data = {
#        'title': 'Главная страница',
#        'menu': menu,
#        'posts': MySite.published.all(),
#        'cat_selected': 0,
#    }
#    return render(request, 'mysite/index.html', context=data)


def handle_uploaded_file(f):
    name = f.name
    ext = ''

    if '.' in name:
        ext = name[name.rindex('.'):]
        name = name[:name.rindex('.')]
    suffix = str(uuid.uuid4())
    with open(f"uploads/{name}_{suffix}{ext}", "wb+") as destination:
        for chunk in f.chunks():
            destination.write(chunk)


@login_required
def about(request):
    contact_list = MySite.published.all()
    paginator = Paginator(contact_list, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            fp = UploadFiles(file=form.cleaned_data['file'])
            fp.save()
    else:
        form = UploadFileForm()
    return render(request, 'mysite/about.html',
                  {'page_obj': page_obj, 'title': 'О сайте'})


@permission_required(perm='mysite.view_mysite', raise_exception=True)
def contact(request):
    return HttpResponse("Обратная связь")


#def addpage(request):
#    if request.method == 'POST':
#        form = AddPostForm(request.POST, request.FILES)
#        if form.is_valid():
#            form.save()
#            return redirect('home')
#    else:
#        form = AddPostForm()
#    return render(request, 'mysite/addpage.html',
#                  {'menu': menu,
#                   'title': 'Добавление статьи',
#                   'form': form})


class AddPage(PermissionRequiredMixin, LoginRequiredMixin, DataMixin, CreateView):
    model = MySite
    permission_required = 'mysite.add_mysite'
    #form_class = AddPostForm
    fields = ['title', 'slug', 'content', 'is_published', 'cat', 'isbn', 'tags']
    template_name = 'mysite/addpage.html'
    success_url = reverse_lazy('home')
    title_page = 'Добавление статьи'

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)


class UpdatePage(DataMixin, UpdateView):
    model = MySite
    permission_required = 'mysite.change_mysite'
    fields = ['title', 'slug', 'content', 'is_published', 'cat', 'isbn', 'tags']
    template_name = 'mysite/addpage.html'
    success_url = reverse_lazy('home')
    title_page = 'Редактирование статьи'


class DeletePage(PermissionRequiredMixin, DataMixin, DeleteView):
    model = MySite
    template_name = 'mysite/deletepage.html'
    success_url = reverse_lazy('home')
    title_page = 'Удаление статьи'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.extra_context)
        return context


def contact(request):
    return HttpResponse("Обратная связь")


def login(request):
    return HttpResponse("Авторизация")


def page_not_found(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

firstsite/mysite/templates/mysite/about.html
{% extends 'mysite/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <nav>
        <ul>
            {% for p in page_obj.paginator.page_range %}
            <li>
                <a href="?page={{ p }}">{{ p }}</a>
            </li> {% endfor %}
        </ul>
    </nav>
    <button type="submit">Отправить</button></p>
</form>

{% endblock %}

firstsite/mysite/templates/mysite/addpage.html
{% extends 'mysite/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-error">{{ form.non_field_errors }}</div>
  {% for f in form %}
  <label class="form-label"
         for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
  <div class="form-error">{{ f.errors }}</div>
  {% endfor %}
  <button type="submit">Добавить</button>
</form>

{% endblock %}

firstsite/mysite/templates/mysite/base.html
{% load static %}
{% load mysite_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'mysite/css/styles.css' %}"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'mysite/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
{% get_menu as menu %}
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
    <tr>
        <td valign=top>
            {% block mainmenu %}
            <div class="header">
                <ul id="mainmenu" class="mainmenu">
                    <li class="logo">
                        <a href="{% url 'home' %}">
                            <div class="logo"></div>
                        </a>
                    </li>
                    {% for m in menu %}
                    <li>
                        <a href="{% url m.url_name %}">{{m.title}}</a>
                    </li>
                    {% endfor %}
                    {% if user.is_authenticated %}
                    <li class="last">
                        <a href="{% url 'users:profile' %}">{{user.username}}</a> |
                        <a href="{% url 'users:logout' %}">Выйти</a>
                    </li>
                    {% else %}
                    <li class="last">
                        <a href="{% url 'users:login' %}">Войти</a> |
                        <a href="{% url 'users:register' %}">Регистрация</a>
                    </li>
                    {% endif %}
                </ul>

                <div class="clear"></div>
            </div>
            {% endblock mainmenu %}

            <table class="table-content" border=0 cellpadding="0" cellspacing="0">
                <tr>

                    <!-- Sidebar слева -->
                    <td valign="top" class="left-chapters">
                        <ul id="leftchapters">
                            {% if cat_selected == 0 or cat_selected is None %}
                            <li class="selected">Все категории</li>
                            {% else %}
                            <li>
                                <a href="{% url 'home' %}">Все категории</a>
                            </li>
                            {% endif %}
                            {% show_categories cat_selected %}
                            <li class="share">
                                <p >Наш канал</p>
                                <a class="share-yt" href="..." target="_blank" rel="nofollow"></a>
                            </li>
                            <li>
                                {% show_all_tags %}
                            </li>
                        </ul>
                    </td>
                    <!-- Конец Sidebar'а -->

                    <td valign="top" class="content">
                        <!-- Хлебные крошки -->
                        {% block breadcrumbs %}
                        {% endblock %}

                        <!-- Блок контента -->
                        <div class="content-text">
                            {% block content %}
                            {% endblock %}
                        </div>
                        <!-- Конец блока контента -->
                    </td>
                </tr>
            </table>
        </td>
    </tr>

    <!-- Footer -->
    <tr>
        <td valign=top>
            <div id="footer">
                <p>&copy; Ваш книжный блог</p>
            </div>
        </td>
    </tr>
</table>
<!-- Конец footer'а и страницы -->
</body>
</html>

firstsite/mysite/templates/mysite/deletepage.html
{% extends 'mysite/base.html' %}

{% block content %}
<h2>{{ title }}</h2>
<p>Вы уверены, что хотите удалить "{{ object }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Да, удалить</button>
    <a href="{% url 'home' %}">Отмена</a>
</form>
{% endblock %}

firstsite/mysite/templates/mysite/index.html
{% extends 'mysite/base.html' %}

{% block content %}
{% include 'mysite/includes/nav.html' %}

<h1>{{title}}</h1>
<p>Содержимое главной страницы</p>
<ul class="list-articles">
    {% for p in posts %}
    <li>
        <div class="article-panel">
            <p class="first">Категория: {{p.cat.name}} |
                автор: {{p.author.username|default:"неизвестен"}}
            </p>
            <p class="last">Дата: {{p.time_update|date:"d-m-Y H:i:s"}}</p>
        </div>
        {% if p.photo %}
        <p ><img class="img-article-left thumb" src="{{p.photo.url}}"></p>
        {% endif %}
        <h2>{{p.title}}</h2>
        {% autoescape off %}
        {{p.content|linebreaks|truncatewords:50}}
        {% endautoescape %}
        <div class="clear"></div>
        <p class="link-read-post">
            <a href="{{ p.get_absolute_url }}">Читать описание</a>
        </p>
    </li>
    {% endfor %}
</ul>
{% if page_obj.has_other_pages %}
<nav class="list-pages">
    <ul>
        {% if page_obj.has_previous %}
        <li class="page-num">
            <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
        </li>
        {% endif %}
        {% for p in paginator.page_range %}
        {% if page_obj.number == p %}
        <li class="page-num page-num-selected">{{ p }}</li>
        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
        <li class="page-num">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-num">
            <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% include 'mysite/includes/nav.html' %}
{% endblock %}

firstsite/mysite/templates/mysite/list_categories.html
{% for cat in cats %}
{% if cat.id == cat_selected %}
 <li
         class="selected">{{cat.name}}</li>
{% else %}
<li>
 <a href="{{ cat.get_absolute_url}}">{{cat.name}}</a>
</li>
{% endif %}
{% endfor %}

firstsite/mysite/templates/mysite/list_tags.html
{% if tags %}
<p >Теги:</p>
<ul class="tags-list">
    {% for t in tags %}
    <li>
        <a href="{{t.get_absolute_url}}">{{t.tag}}</a>
    </li>
    {% endfor %}
</ul>
{% endif %}

firstsite/mysite/templates/mysite/post.html
{% extends 'mysite/base.html' %}

{% block breadcrumbs %}
<!-- Теги -->
{{ perms }}

{% if perms.mysite.change_mysite %}
<p >
    <a href="{% url 'edit_page' post.slug %}">Редактировать</a>
</p>
{% endif %}

{% with post.tags.all as tags %}
{% if tags %}
<ul class="tags-list">
<li>Теги:</li>
{% for t in tags %}
<li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
{% endfor %}
</ul>
{% endif %}
{% endwith %}
{% endblock %}
{% block content %}
<h1>{{post.title}}</h1>
{% if post.photo %}
<p ><img class="img-article-left" src="{{post.photo.url}}"></p>
{% endif %}

{% autoescape off %}
{{post.content|linebreaks}}
{% endautoescape %}

{% endblock %}